Updated mk script to not run mkr if mkb failed

diff --git a/scripts/mk b/scripts/mk
--- a/scripts/mk
+++ b/scripts/mk
@@ -11,6 +11,5 @@ if [[ ! -f .mk ]]; then
 	exit -1
 fi
 
-mkb
-mkr
+mkb && mkr || echo "Error during build!"
 
